# Generated by Django 4.2.7 on 2026-02-09 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('subtheme', models.CharField(blank=True, max_length=100, verbose_name='Sous-thème')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'subtheme', 'question'],
            },
        ),
        migrations.CreateModel(
            name='FAQVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tfidf_vector', models.JSONField(verbose_name='Vecteur TF-IDF')),
                ('norm', models.FloatField(verbose_name='Norme du vecteur')),
                ('computed_at', models.DateTimeField(auto_now_add=True, verbose_name='Calculé le')),
            ],
            options={
                'verbose_name': 'Vecteur FAQ',
                'verbose_name_plural': 'Vecteurs FAQ',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('correction', 'Correction'), ('suggestion', 'Suggestion'), ('positive', 'Positif'), ('negative', 'Négatif'), ('question', 'Question')], max_length=20, verbose_name='Type de feedback')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Score (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('resolved', models.BooleanField(default=False, verbose_name='Résolu')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.faq', verbose_name='FAQ concernée')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
