# Generated by Django 4.2.7 on 2026-02-09 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('subtheme', models.CharField(blank=True, max_length=100, verbose_name='Sous-thème')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('popularity', models.IntegerField(default=0, verbose_name='Popularité')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='faq.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'subtheme', 'question'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('positif', 'Positif'), ('negatif', 'Négatif')], max_length=20, verbose_name='Type')),
                ('question_utilisateur', models.TextField(verbose_name='Question utilisateur')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('score_similarite', models.FloatField(blank=True, null=True, verbose_name='Score de similarité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.faq', verbose_name='FAQ concernée')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tfidf_vector', models.JSONField(verbose_name='Vecteur TF-IDF')),
                ('norm', models.FloatField(verbose_name='Norme du vecteur')),
                ('computed_at', models.DateTimeField(auto_now_add=True, verbose_name='Calculé le')),
                ('faq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector', to='faq.faq', verbose_name='FAQ associée')),
            ],
            options={
                'verbose_name': 'Vecteur FAQ',
                'verbose_name_plural': 'Vecteurs FAQ',
            },
        ),
    ]
