# Generated by Django 4.2.7 on 2026-04-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rag_method',
            field=models.CharField(choices=[('TF-IDF', 'TF-IDF'), ('RAG', 'RAG')], default='TF-IDF', max_length=10),
        ),
    ]
